import Groq from "groq-sdk"
import { AIProvider } from "./ai-provider"
import { RecommendationItem } from "@/types/analysis"

interface RecommendationPromptContext {
  systemPrompt: string
  userPrompt: string
}

/**
 * Calls the Groq API using the official Groq SDK with timeout, retry logic (max 1 retry),
 * and parses response safely into typed Recommendation items.
 *
 * @param context Prompt context generated by prompt-builder.ts.
 */
export async function generateOperationalRecommendation(
  context: RecommendationPromptContext
): Promise<RecommendationItem[]> {
  const apiKey = process.env.GROQ_API_KEY
  if (!apiKey) {
    console.warn("GROQ_API_KEY environment variable is not defined. Skipping operational recommendation generation.")
    return []
  }
  console.log(`[analyze] GROQ key loaded: ${apiKey.substring(0, 8)}${'*'.repeat(Math.max(0, apiKey.length - 8))}`)

  const groq = new Groq({ apiKey })

  const requestPayload = {
    model: "llama-3.1-8b-instant",
    messages: [
      { role: "system" as const, content: context.systemPrompt },
      { role: "user" as const, content: context.userPrompt },
    ],
    temperature: 0.1,
    response_format: { type: "json_object" as const },
  }

  const requestOptions = {
    timeout: 10000, // 10-second operational timeout limit
  }

  let attempt = 0
  const maxAttempts = 2 // 1 initial attempt + 1 retry maximum

  while (attempt < maxAttempts) {
    attempt++
    try {
      const response = await groq.chat.completions.create(requestPayload, requestOptions)
      const content = response.choices?.[0]?.message?.content
      if (!content) {
        throw new Error("Empty message content returned from Groq API completion.")
      }

      const parsed = JSON.parse(content)
      const items = Array.isArray(parsed) ? parsed : parsed.recommendations

      if (!Array.isArray(items)) {
        throw new Error("Invalid completion schema format: Root object must contain 'recommendations' array.")
      }

      return items.map((item: any, index: number) => ({
        id: String(item.id || `ai-rec-${index}-${Math.random().toString(36).substring(2, 6)}`),
        action: String(item.action || item.action_plan || ""),
        reason: String(item.reason || item.trigger_reason || ""),
        expectedImpact: String(item.expectedImpact || item.projected_impact || ""),
        confidence: Number(item.confidence || item.inference_confidence || 90),
        priority: (String(item.priority || item.urgency_level || "optimal").toLowerCase()) as any,
      }))
    } catch (error) {
      console.warn(`Groq SDK completion request attempt ${attempt} failed:`, error)
      if (attempt >= maxAttempts) {
        console.error("All Groq recommendation requests failed. Returning fallback empty array.")
        return []
      }
    }
  }

  return []
}

export class GroqProvider implements AIProvider {
  readonly name = "Groq"

  async generateRecommendations(systemPrompt: string, userPrompt: string): Promise<RecommendationItem[]> {
    return generateOperationalRecommendation({ systemPrompt, userPrompt })
  }
}
